### PR TITLE
Ray executor can request resources for workers

### PR DESCRIPTION
**Pull request by zigaLuksic**
Kinda hard to test :/ ideas welcome

### CODE REVIEW

**Review by mlubej — APPROVED** [review]
basically what was already discussed in the pair session

**Comment by zigaLuksic** [comment]
> I'm also not sure about testing this without actually properly running things on the cluster.

i guess we could try and request too much of a resource and then try and catch the warning?

**Comment by mlubej** [comment]
> i guess we could try and request too much of a resource and then try and catch the warning?

Seems like if you ask for a non-existing resource, or for a larger resource chunk than it exists, the process just stalls

**Comment by zigaLuksic** [comment]
> > i guess we could try and request too much of a resource and then try and catch the warning?
> 
> Seems like if you ask for a non-existing resource, or for a larger resource chunk than it exists, the process just stalls

yeah, but on the cluster it returns a warning. But i cant remember if it does that inside the python runtime as well, might just be a log message.

**Comment by mlubej** [comment]
No further ideas about the tests...

**Review by mlubej — APPROVED** [review]

**Pull request merged**
