### PR TITLE
Add isort to eolearn

### PR DESCRIPTION
**Pull request by mlubej**
Changes:
- sorted the packages in the requirements files alphabetically
- `black` was missing from the `requirements-dev.txt`
- added also `isort` and ran it on the repo
  - `sentinelhub` was added as a first party package - higher than local, lower than third party

### CODE REVIEW

**Comment by mlubej** [comment]
There are some issue relating to the relative imports (examples below). What is the direction in which `eo-learn` is going with these? My personal preference would be to always use absolute imports. I know there are pros and cons to both, but the community seems to prefer the absolute imports over relative ones.



```
************* Module eolearn.visualization.eopatch
visualization/eolearn/visualization/eopatch.py:23:0: C0411: third party import "from eolearn.core import EOPatch, FeatureType" should be placed before "from .eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
************* Module eolearn.visualization.extra.hvplot
visualization/eolearn/visualization/extra/hvplot.py:40:0: C0411: third party import "from eolearn.core import EOPatch, FeatureType, FeatureTypeSet" should be placed before "from ..eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
visualization/eolearn/visualization/extra/hvplot.py:41:0: C0411: third party import "from eolearn.core.utils.parsing import parse_feature" should be placed before "from ..eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
```

**Comment by mlubej** [comment]
Ah, I get it, the absolute imports in this case look really messy. I solved this using a custom section in `isort`:

third party > first party > local absolute > local relative

**Comment by zigaLuksic** [comment]
> There are some issue relating to the relative imports (examples below). What is the direction in which `eo-learn` is going with these? My personal preference would be to always use absolute imports. I know there are pros and cons to both, but the community seems to prefer the absolute imports over relative ones.
> 
> ```
> ************* Module eolearn.visualization.eopatch
> visualization/eolearn/visualization/eopatch.py:23:0: C0411: third party import "from eolearn.core import EOPatch, FeatureType" should be placed before "from .eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
> ************* Module eolearn.visualization.extra.hvplot
> visualization/eolearn/visualization/extra/hvplot.py:40:0: C0411: third party import "from eolearn.core import EOPatch, FeatureType, FeatureTypeSet" should be placed before "from ..eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
> visualization/eolearn/visualization/extra/hvplot.py:41:0: C0411: third party import "from eolearn.core.utils.parsing import parse_feature" should be placed before "from ..eopatch_base import BaseEOPatchVisualization, BasePlotConfig" (wrong-import-order)
> ```

We tend to use relative imports for same package and absolute for other packages (since eolearn.core and eolearn.visualisation are not submodules but different packages).

**Review by zigaLuksic — COMMENTED** [review]
Please also add a github action for checking import sorting (like we do in eo-grow [here](https://github.com/sentinel-hub/eo-grow/blob/develop/.github/workflows/ci_action.yml#L50))

**Comment by mlubej** [comment]
> We tend to use relative imports for same package and absolute for other packages (since eolearn.core and eolearn.visualisation are not submodules but different packages).

Would it be better then if other eolearn packages are treated as first party packages, alongside `sentinelhub` ?

**Comment by zigaLuksic** [comment]
> I added the `isort` check, but if you'd prefer to have both checks under `check-code-formatting`, I can put them under the same action.

So far we're going for separate actions (so that if isort fails you'll still see that black fails as well). Might change in the future if it becomes unwieldy

**Review by AleksMat — APPROVED** [review]

**Pull request merged**
