### PR TITLE
Fix remaining annotations to new-style

### PR DESCRIPTION
**Pull request by zigaLuksic**
Some files were missed by the FA flag

### CODE REVIEW

**Review by mlubej — COMMENTED** [review]
Why were they missed? What kind of manual action did you have to do to fix the remaining ones?

**Comment by zigaLuksic** [comment]
the flag doesnt seem to be working 100% of the time
i searched for all occurences of `Union`, `Dict`, `Tuple` and `List` (the main changes)

**Comment by mlubej** [comment]
> the flag doesnt seem to be working 100% of the time
> i searched for all occurences of `Union`, `Dict`, `Tuple` and `List` (the main changes)

Perhaps then it _would_ be better to just add `from __future__ import annotations` everywhere? especially since you mentioned that the type aliases don't work correctly without it in the docs.

I'm mentioning this because it seems you missed a few which seem to get corrected if I add the future annotation import under the `tool.ruff.isort` required-imports:
- https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/core/eolearn/tests/test_utils/test_testing.py#L35
- https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/core/eolearn/tests/test_utils/test_testing.py#L78
- https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/docs/source/conf.py#LL381C44-L381C44
- https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/docs/source/conf.py#L435-L441

Unless you intentionally left those out

**Comment by zigaLuksic** [comment]
> > the flag doesnt seem to be working 100% of the time
> > i searched for all occurences of `Union`, `Dict`, `Tuple` and `List` (the main changes)
> 
> Perhaps then it _would_ be better to just add `from __future__ import annotations` everywhere? especially since you mentioned that the type aliases don't work correctly without it in the docs.
> 
> I'm mentioning this also because it seems you missed a few which seem to get corrected if I add the future annotation import under the `tool.ruff.isort` required-imports:
> 
>     * https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/core/eolearn/tests/test_utils/test_testing.py#L35
> 
>     * https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/core/eolearn/tests/test_utils/test_testing.py#L78
> 
>     * https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/docs/source/conf.py#LL381C44-L381C44
> 
>     * https://github.com/sentinel-hub/eo-learn/blob/fix-remaining-annotations/docs/source/conf.py#L435-L441
> 
> 
> Unless you intentionally left those out

The `test_testing` was not intentional, the conf.py was (i'd add an ignore to it)
For eo-learn it might actually be reasonable to do this. In sh-py and eo-grow there are conflicts due to certain dataclasses, but in eo-learn this should work just fine

**Comment by zigaLuksic** [comment]
adding the required import adds it to a further 58 files. I assume we want this to be autofixable?

**Comment by mlubej** [comment]
> adding the required import adds it to a further 58 files. I assume we want this to be autofixable?

I would say so, yes. This ignores `__init__.py` files?

**Comment by zigaLuksic** [comment]
> > adding the required import adds it to a further 58 files. I assume we want this to be autofixable?
> 
> I would say so, yes. This ignores `__init__.py` files?

I made it ignore init files, the conf files and notebooks.

**Review by mlubej — APPROVED** [review]

**Pull request merged**
