### PR TITLE
Add superresolution example

### PR DESCRIPTION
**Pull request by drewbo**
Example using Spacenet data + Sentinel 2 to prepare superresolution training. I'm cleaning up the actual training script and will upload. Should this go in `ml_tools` or its own folder?

### CODE REVIEW

**Comment by devisperessutti** [comment]
I would move this to the examples folder

**Comment by drewbo** [comment]
@devisperessutti to clarify, right now it's in `examples/ml_tools/SuperResolutionPrep.ipynb`, do you think it's good there or should it get a new examples folder like `examples/superresolution/DataPrep.ipynb`?

**Comment by devisperessutti** [comment]
Sorry @drewbo, thought it was in `ml_tools` sub-package.

I would go with the second option of renaming the folder to `examples/superresolution/DataPrep.ipynb`

**Comment by devisperessutti** [comment]
Minor comments to be addressed:

 * in `DataPrep.ipynb` can you please rename `add_l1c` to `add_l2a`, since the `S2L2AWCSInput` task is used
 * in `Train.ipynb`, can you please add a description of the steps taken in the notebook, as well as a list of requirements needed to reproduce the results (i.e. installing `fastai` as is not part of `eo-learn`)
 * I was thinking that having the framework name in the folder (i.e. `super-resolution-fastai`) can be useful for users when browsing the examples (we'll try to be consistent with the other examples) 

The notebooks look very good otherwise

**Comment by drewbo** [comment]
@devisperessutti thanks for the helpful feedback. I made the requested changes, please merge when ready

**Comment by devisperessutti** [comment]
great, thanks for the changes @drewbo

**Pull request merged**
