### PR TITLE
Limit geopandas version to <1

### PR DESCRIPTION
**Pull request by zigaLuksic**

### CODE REVIEW

**Review by batic — APPROVED** [review]

**Comment by zigaLuksic** [comment]
@batic the pylint errors are complete nonsense
I was thinking of just merging with a failed build, but i can just disable pylint for this release

**Comment by zigaLuksic** [comment]
> @batic the pylint errors are complete nonsense I was thinking of just merging with a failed build, but i can just disable pylint for this release

I'm leaning towards releasing with a failing build, because disabling pylint doesnt really solve anything, and this way we can reinvestigate when i get back.

**Comment by zigaLuksic** [comment]
others are experiencing the same pylint issues, so i'm going forward with the release

**Comment by mlubej** [comment]
Just linking for transparency: https://github.com/pylint-dev/pylint/issues/9751

Probably a pylint bug or something

**Pull request merged**
