### PR TITLE
[WIP] add TMS input

### PR DESCRIPTION
**Pull request by vincentsarago**
Work In Progress 

replace #84

### CODE REVIEW

**Comment by devisperessutti** [comment]
Hi @vincentsarago 

Do you perhaps have an ETA on this?

Thank you!

**Comment by vincentsarago** [comment]
@devisperessutti 👋 sorry for letting this stale, I'll try to finish this in January!  cc @drewbo

**Comment by mlubej** [comment]
@vincentsarago is this still a WIP? Do you intend to finish?

@devisperessutti do you think this task would fit well in eo-learn? If yes, we can fork the branch and take over.

**Comment by vincentsarago** [comment]
I’m so sorry this didn’t move forward. I still think this would be a great addition it not sure when I’ll have time to finish 😢

**Comment by mlubej** [comment]
> I’m so sorry this didn’t move forward. I still think this would be a great addition it not sure when I’ll have time to finish cry

@vincentsarago no worries, just clearing up the PR list a bit. In case that you're not sure when you'll work on this, would you mind if we close it until it comes back around? It can always be reopened later, if need be.

**Pull request closed without merging**
